#! /bin/bash
# Crisidev Cloud Firewall

echo "Setting up firewall rules..."
#-------------------------------------------------------------------------------
# Script variables
#-------------------------------------------------------------------------------
IF_WAN=eth0
IF_BR=br0
IF_VPN=tun0
#-------------------------------------------------------------------------------

#-------------------------------------------------------------------------------
# Adjust /proc
#-------------------------------------------------------------------------------
echo -ne "\t\tAdjusting /proc..."

echo 1 > /proc/sys/net/ipv4/icmp_echo_ignore_broadcasts
echo 1 > /proc/sys/net/ipv4/icmp_ignore_bogus_error_responses
echo 1 > /proc/sys/net/ipv4/conf/all/secure_redirects
echo 1 > /proc/sys/net/ipv4/conf/all/send_redirects
#echo 0 > /proc/sys/net/ipv4/tcp_syncookies
echo 1 > /proc/sys/net/ipv4/conf/all/accept_source_route
echo 1 > /proc/sys/net/ipv4/conf/all/forwarding
echo 0 > /proc/sys/net/ipv4/conf/all/log_martians
echo 1 > /proc/sys/net/ipv4/conf/all/rp_filter
echo 1 > /proc/sys/net/ipv4/ip_forward

echo "done."
#-------------------------------------------------------------------------------

#-------------------------------------------------------------------------------
# Flush existing settings
#-------------------------------------------------------------------------------
echo -ne "\t\tFlushing existing settings..."

iptables -F INPUT
iptables -F OUTPUT
iptables -F FORWARD
iptables -t nat -F
iptables -t mangle -F

echo "done."
#-------------------------------------------------------------------------------

#-------------------------------------------------------------------------------
# Table policies
#-------------------------------------------------------------------------------
echo -ne "\t\tSetting up tables policies..."

iptables -P INPUT DROP
iptables -P OUTPUT ACCEPT
iptables -P FORWARD ACCEPT

echo "done."
#-------------------------------------------------------------------------------

#-------------------------------------------------------------------------------
# Loopback traffic
#-------------------------------------------------------------------------------
iptables -A INPUT -i lo -j ACCEPT
iptables -A OUTPUT -o lo -j ACCEPT
#-------------------------------------------------------------------------------

#-------------------------------------------------------------------------------
# Icmp settings
#-------------------------------------------------------------------------------
echo -ne "\t\tSetting up icmp rules..."

# to fw
iptables -A INPUT -p icmp -m state --state ESTABLISHED,RELATED -j ACCEPT
iptables -A INPUT -p icmp --icmp-type echo-request -m length --length 128:65535 -j DROP
iptables -A INPUT -p icmp --icmp-type echo-request -m limit --limit 1/s -j ACCEPT

# from fw
iptables -A OUTPUT -p icmp -m state --state ESTABLISHED,RELATED -j ACCEPT
iptables -A OUTPUT -p icmp --icmp-type echo-request -m length --length 128:65535 -j DROP
iptables -A OUTPUT -p icmp --icmp-type echo-request -m limit --limit 1/s -j ACCEPT

# trough fw
iptables -A FORWARD -p icmp -m state --state ESTABLISHED,RELATED -j ACCEPT
iptables -A FORWARD -i $IF_WAN -p icmp --icmp-type destination-unreachable -m limit --limit 1/s -j ACCEPT
iptables -A FORWARD -i $IF_WAN -p icmp --icmp-type redirect -m limit --limit 1/s -j ACCEPT
iptables -A FORWARD -i $IF_WAN -p icmp --icmp-type time-exceeded -m limit --limit 1/s -j ACCEPT

echo "done."
#-------------------------------------------------------------------------------

#-------------------------------------------------------------------------------
# Filter settings
#-------------------------------------------------------------------------------
echo -ne "\t\tSetting up FILTER rules..."

# from WAN to FW
iptables -A INPUT -i $IF_BR -j ACCEPT
iptables -A INPUT -i $IF_VPN -j ACCEPT
iptables -A INPUT -i $IF_WAN -m state --state ESTABLISHED,RELATED -j ACCEPT
iptables -A INPUT -i $IF_WAN -p tcp --dport 22 -j ACCEPT                           # ssh
iptables -A INPUT -i $IF_WAN -p tcp --dport 80 -j ACCEPT                           # http
iptables -A INPUT -i $IF_WAN -p tcp --dport 443 -j ACCEPT                          # https
iptables -A INPUT -i $IF_WAN -p tcp --dport 655 -j ACCEPT                          # tinc
#iptables -A INPUT -i $IF_WAN -p tcp --dport 7002 -j ACCEPT                          # znc

echo "done."
#-------------------------------------------------------------------------------

#-------------------------------------------------------------------------------
# NAT settings
#-------------------------------------------------------------------------------
echo -ne "\t\tSetting up NAT rules..."

iptables -t nat -A POSTROUTING -j MASQUERADE

# TCP NAT
RETVAL=0

iptables -t nat -A PREROUTING -i eth0 -p tcp --dport 1022 -j DNAT --to $(dig +time=2 +tries=1 +short git.crisidev.org):22 -m comment --comment "git.crisidev.org"
RETVAL=$(expr ${RETVAL} + $?)

iptables -t nat -A PREROUTING -i eth0 -p tcp --dport 2222 -j DNAT --to $(dig +time=2 +tries=1 +short git.crisidev.org):22 -m comment --comment "git.crisidev.org"
RETVAL=$(expr ${RETVAL} + $?)


iptables -t nat -A PREROUTING -i eth0 -p tcp --dport 80 -j DNAT --to $(dig +time=2 +tries=1 +short nginx.crisidev.org):80 -m comment --comment "nginx.crisidev.org"
RETVAL=$(expr ${RETVAL} + $?)


iptables -t nat -A PREROUTING -i eth0 -p tcp --dport 1022 -j DNAT --to $(dig +time=2 +tries=1 +short node3.crisidev.org):22 -m comment --comment "node3.crisidev.org"
RETVAL=$(expr ${RETVAL} + $?)


iptables -t nat -A PREROUTING -i eth0 -p tcp --dport 1022 -j DNAT --to $(dig +time=2 +tries=1 +short irssi.crisidev.org):22 -m comment --comment "irssi.crisidev.org"
RETVAL=$(expr ${RETVAL} + $?)


iptables -t nat -A PREROUTING -i eth0 -p tcp --dport 1022 -j DNAT --to $(dig +time=2 +tries=1 +short node1.crisidev.org):22 -m comment --comment "node1.crisidev.org"
RETVAL=$(expr ${RETVAL} + $?)


iptables -t nat -A PREROUTING -i eth0 -p tcp --dport 1022 -j DNAT --to $(dig +time=2 +tries=1 +short node0.crisidev.org):22 -m comment --comment "node0.crisidev.org"
RETVAL=$(expr ${RETVAL} + $?)


iptables -t nat -A PREROUTING -i eth0 -p tcp --dport 443 -j DNAT --to $(dig +time=2 +tries=1 +short sslh.crisidev.org):443 -m comment --comment "sslh.crisidev.org"
RETVAL=$(expr ${RETVAL} + $?)


iptables -t nat -A PREROUTING -i eth0 -p tcp --dport 1022 -j DNAT --to $(dig +time=2 +tries=1 +short node2.crisidev.org):22 -m comment --comment "node2.crisidev.org"
RETVAL=$(expr ${RETVAL} + $?)


iptables -t nat -A PREROUTING -i eth0 -p tcp --dport 7002 -j DNAT --to $(dig +time=2 +tries=1 +short znc.crisidev.org):7002 -m comment --comment "znc.crisidev.org"
RETVAL=$(expr ${RETVAL} + $?)


# UDP NAT

iptables -t nat -A PREROUTING -i eth0 -p udp --dport 53 -j DNAT --to $(dig +time=2 +tries=1 +short iodine.crisidev.org):53 -m comment --comment "iodine.crisidev.org"
RETVAL=$(expr ${RETVAL} + $?)


echo "done."
#-------------------------------------------------------------------------------

echo "The firewall is up."
exit ${RETVAL}