global:
  scrape_interval: '60s'

scrape_configs:
- job_name: 'prometheus'
  target_groups:
  - targets: ['localhost:9090']
    labels:
      job: 'prometheus'

- job_name: 'node_exporter'
  target_groups:
  - targets: ['shuttle.crisidev.org:9100','node0.crisidev.org:9100','node1.crisidev.org:9100','snatch.crisidev.org:9100']
    labels:
      job: 'node'

- job_name: 'cadvisor'
  target_groups:
  - targets: ['node0.crisidev.org:8080','node1.crisidev.org:8080','snatch.crisidev.org:8080']
    labels:
      job: 'cadvisor'

- job_name: 'etcd2'
  target_groups:
  - targets: ['node0.crisidev.org:4001','node1.crisidev.org:4001','snatch.crisidev.org:4001','shuttle.crisidev.org:4001','hubble.crisidev.org:4001']
    labels:
      job: 'etcd2'

- job_name: 'skydns'
  target_groups:
  - targets: ['node0.crisidev.org:3000','node1.crisidev.org:3000','snatch.crisidev.org:3000']
    labels:
      job: 'skydns'
